const {
  EfficiencyPreference,
  Person,
  Podrazdelenie,
  Zvanie,
  Category,
  UprazhnenieRealValuesType,
  Uprazhnenie,
  UprazhnenieStandard,
} = require("./sequelize");

const fillDefaultsEfficiencyPreferences = () => {
  EfficiencyPreference.bulkCreate([
    { id: 1, name: "Больше - лучше" },
    { id: 2, name: "Меньше - лучше" },
  ]);
};

const fillDefaultsPodrazdeleniya = () => {
  Podrazdelenie.bulkCreate([
    {
      id: 1,
      name: "ВНИЦ || Управление центра",
    },
    { id: 2, name: "ВНИЦ || Отдел научной информации и инноваций" },
    { id: 3, name: "ВНИЦ || Служба научно-издательского обеспечения" },
    {
      id: 4,
      name: "ВНИЦ || Научно-исследовательский институт военного искусства",
    },
    {
      id: 5,
      name: "ВНИЦ || Управление исследования военной истории и педагогики ",
    },
    {
      id: 6,
      name: "ВНИЦ || Управление исследования военной истории и педагогики",
    },
    { id: 7, name: "ВНИЦ || Управление исследования ВиВТ" },
    { id: 8, name: "ВНИЦ || Инженерно-техническое управление (технопарк)" },
    { id: 9, name: "ВНИЦ || Управление информационных технологий" },
    {
      id: 10,
      name: "ВНИЦ || Лаборатория исследования, проектирования и разработки программного обеспечения",
    },
    {
      id: 11,
      name: "ВНИЦ || Лаборатория исследования на информационную безопасность",
    },
    { id: 12, name: "ВНИЦ || Военно-научный взвод" },
    { id: 13, name: "РОиО || Управление роты" },
    { id: 14, name: "РОиО || Взвод охраны" },
    {
      id: 15,
      name: "РОиО || Взвод связи и автоматизированных систем управления",
    },
    { id: 16, name: "РОиО || Взвод транспортного обеспечения" },
    { id: 17, name: "РОиО || Склады" },
    { id: 18, name: "РОиО || Солдаты срочной службы" },
    {
      id: 19,
      name: "Управления || Управление боевой готовности и службы войск",
    },
    {
      id: 20,
      name: "Управления || Отдел службы войск управления боевой готовности и службы войск",
    },
    {
      id: 21,
      name: "Управления || Отдел связи и автоматизированных систем управления управления боевой готовности и службы войск",
    },
    {
      id: 22,
      name: "Управления || Отделение организационной и мобилизационной работы управления боевой готовности и службы войск",
    },
    {
      id: 23,
      name: "Управления || Отдел организации и планирования учебного процесса учебно-методического управления",
    },
    {
      id: 24,
      name: "Управления || Докторантура учебно-методического управления",
    },
    {
      id: 25,
      name: "Управления || Отдел курсовой подготовки учебно-методического управления",
    },
    {
      id: 26,
      name: "Управления || Служба обеспечения техническими средствами обучения учебно-методического управления",
    },
    {
      id: 27,
      name: "Управления || Управление воспитательной и идеологической работы",
    },
    {
      id: 28,
      name: "Управления || Отдел международного сотрудничества управления воспитательной и идеологической работы",
    },
    {
      id: 29,
      name: "Управления || Управление материально-технического обеспечения",
    },
    {
      id: 30,
      name: "Управления || Отдел защиты государственных секретов и информационной безопасности",
    },
    { id: 31, name: "Управления || Отдел по работе с персоналом" },
    { id: 32, name: "Управления || Финансовый отдел" },
    { id: 33, name: "Управления || Медицинская служба" },
    { id: 34, name: "Управления || Юридическая служба" },
    { id: 35, name: "Начальники факультетов" },
    { id: 36, name: "Начальники кафедры" },
  ]);
};

const fillDefaultsPersons = () => {
  Person.bulkCreate([
    // РОиО || Управление роты
    {
      lName: "Жабинов",
      fName: "Д",
      sName: "Д",
      zvanieId: 12,
      podrazdelenieId: 13,
      isMale: true,
      categoryId: 5,
    },
    {
      lName: "Есентай",
      fName: "Ж",
      sName: "Е",
      zvanieId: 11,
      podrazdelenieId: 13,
      isMale: true,
      categoryId: 3,
    },
    {
      lName: "Сагалов",
      fName: "К",
      sName: "Б",
      zvanieId: 5,
      podrazdelenieId: 13,
      isMale: true,
      categoryId: 4,
    },
    {
      lName: "Капбаров",
      fName: "Н",
      sName: "А",
      zvanieId: 5,
      podrazdelenieId: 13,
      isMale: true,
      categoryId: 4,
    },

    // РОиО || Взвод охраны
    {
      lName: "Бегім",
      fName: "Б",
      sName: "Ж",
      zvanieId: 5,
      podrazdelenieId: 14,
      isMale: true,
      categoryId: 2,
    },
    {
      lName: "Ордабек",
      fName: "Ө",
      sName: "К",
      zvanieId: 5,
      podrazdelenieId: 14,
      isMale: true,
      categoryId: 2,
    },
    {
      lName: "Имашев",
      fName: "М",
      sName: "Б",
      zvanieId: 4,
      podrazdelenieId: 14,
      isMale: true,
      categoryId: 2,
    },
    {
      lName: "Ергали",
      fName: "Д",
      sName: "Ж",
      zvanieId: 3,
      podrazdelenieId: 14,
      isMale: true,
      categoryId: 2,
    },
    {
      lName: "Аманжолов",
      fName: "А",
      sName: "А",
      zvanieId: 3,
      podrazdelenieId: 14,
      isMale: true,
      categoryId: 1,
    },
    {
      lName: "Миясар",
      fName: "А",
      sName: "А",
      zvanieId: 2,
      podrazdelenieId: 14,
      isMale: true,
      categoryId: 1,
    },
    {
      lName: "Есенжолов",
      fName: "Н",
      sName: "Н",
      zvanieId: 5,
      podrazdelenieId: 14,
      isMale: true,
      categoryId: 4,
    },
    {
      lName: "Бектасов",
      fName: "Ш",
      sName: "А",
      zvanieId: 6,
      podrazdelenieId: 14,
      isMale: true,
      categoryId: 4,
    },
    {
      lName: "Рахимов",
      fName: "А",
      sName: "Т",
      zvanieId: 4,
      podrazdelenieId: 14,
      isMale: true,
      categoryId: 3,
    },
    {
      lName: "Жамкенов",
      fName: "Н",
      sName: "Т",
      zvanieId: 3,
      podrazdelenieId: 14,
      isMale: true,
      categoryId: 2,
    },
    {
      lName: "Мусипов",
      fName: "Н",
      sName: "Т",
      zvanieId: 4,
      podrazdelenieId: 14,
      isMale: true,
      categoryId: 3,
    },
    {
      lName: "Закиров",
      fName: "А",
      sName: "Р",
      zvanieId: 3,
      podrazdelenieId: 14,
      isMale: true,
      categoryId: 3,
    },
    {
      lName: "Багдаулет",
      fName: "Е",
      sName: "М",
      zvanieId: 3,
      podrazdelenieId: 14,
      isMale: true,
      categoryId: 2,
    },
    {
      lName: "Антайбеков",
      fName: "Р",
      sName: "О",
      zvanieId: 4,
      podrazdelenieId: 14,
      isMale: true,
      categoryId: 2,
    },
    {
      lName: "Сейтжанов",
      fName: "А",
      sName: "Б",
      zvanieId: 4,
      podrazdelenieId: 14,
      isMale: true,
      categoryId: 2,
    },
    {
      lName: "Жабинов",
      fName: "Д",
      sName: "Д",
      zvanieId: 5,
      podrazdelenieId: 14,
      isMale: true,
      categoryId: 5,
    },
    {
      lName: "Лепесова",
      fName: "А",
      sName: "С",
      zvanieId: 2,
      podrazdelenieId: 14,
      isMale: false,
      categoryId: 11,
    },
    {
      lName: "Бексултан",
      fName: "А",
      sName: "Б",
      zvanieId: 2,
      podrazdelenieId: 14,
      isMale: true,
      categoryId: 1,
    },
    {
      lName: "Калиянов",
      fName: "А",
      sName: "С",
      zvanieId: 4,
      podrazdelenieId: 14,
      isMale: true,
      categoryId: 3,
    },
    {
      lName: "Есжанов",
      fName: "А",
      sName: "О",
      zvanieId: 2,
      podrazdelenieId: 14,
      isMale: true,
      categoryId: 3,
    },
    {
      lName: "Махамбетов",
      fName: "Р",
      sName: "Х",
      zvanieId: 4,
      podrazdelenieId: 14,
      isMale: true,
      categoryId: 4,
    },

    // РОиО || Взвод связи и автоматизированных систем управления
    {
      lName: "Байтай",
      fName: "Ж",
      sName: "А",
      zvanieId: 6,
      podrazdelenieId: 15,
      isMale: true,
      categoryId: 3,
    },
    {
      lName: "Нутбаев",
      fName: "Д",
      sName: "О",
      zvanieId: 3,
      podrazdelenieId: 15,
      isMale: true,
      categoryId: 3,
    },
    {
      lName: "Дутбаев",
      fName: "Б",
      sName: "Т",
      zvanieId: 3,
      podrazdelenieId: 15,
      isMale: true,
      categoryId: 3,
    },
    {
      lName: "Шамшиева",
      fName: "Н",
      sName: "Б",
      zvanieId: 3,
      podrazdelenieId: 15,
      isMale: false,
      categoryId: 11,
    },

    // РОиО || Взвод транспортного обеспечения
    {
      lName: "Солтахов",
      fName: "К",
      sName: "Р",
      zvanieId: 6,
      podrazdelenieId: 16,
      isMale: true,
      categoryId: 5,
    },
    {
      lName: "Мурастов",
      fName: "А",
      sName: "А",
      zvanieId: 5,
      podrazdelenieId: 16,
      isMale: true,
      categoryId: 4,
    },
    {
      lName: "Нартай",
      fName: "Б",
      sName: "А",
      zvanieId: 38,
      podrazdelenieId: 16,
      isMale: true,
      categoryId: 6,
    },
    {
      lName: "Бектасов",
      fName: "О",
      sName: "А",
      zvanieId: 5,
      podrazdelenieId: 16,
      isMale: true,
      categoryId: 3,
    },
    {
      lName: "Тустикбаев",
      fName: "Р",
      sName: "Н",
      zvanieId: 5,
      podrazdelenieId: 16,
      isMale: true,
      categoryId: 3,
    },
    {
      lName: "Серикбаев",
      fName: "Б",
      sName: "Ж",
      zvanieId: 5,
      podrazdelenieId: 16,
      isMale: true,
      categoryId: 4,
    },
    {
      lName: "Муканов",
      fName: "Д",
      sName: "Н",
      zvanieId: 4,
      podrazdelenieId: 16,
      isMale: true,
      categoryId: 4,
    },
    {
      lName: "Карипуллаев",
      fName: "Е",
      sName: "С",
      zvanieId: 2,
      podrazdelenieId: 16,
      isMale: true,
      categoryId: 2,
    },
    {
      lName: "Сейтен",
      fName: "Н",
      sName: "Н",
      zvanieId: 2,
      podrazdelenieId: 16,
      isMale: true,
      categoryId: 2,
    },
    {
      lName: "Түктібаев",
      fName: "Ы",
      sName: "А",
      zvanieId: 2,
      podrazdelenieId: 16,
      isMale: true,
      categoryId: 2,
    },
    {
      lName: "Шөкенаев",
      fName: "А",
      sName: "С",
      zvanieId: 5,
      podrazdelenieId: 16,
      isMale: true,
      categoryId: 4,
    },

    // РОиО || Склады
    {
      lName: "Ахметов",
      fName: "А",
      sName: "Е",
      zvanieId: 4,
      podrazdelenieId: 17,
      isMale: true,
      categoryId: 2,
    },
    {
      lName: "Таласбекова",
      fName: "Ж",
      sName: "А",
      zvanieId: 3,
      podrazdelenieId: 17,
      isMale: false,
      categoryId: 11,
    },
    {
      lName: "Анарбекова",
      fName: "М",
      sName: "К",
      zvanieId: 3,
      podrazdelenieId: 17,
      isMale: false,
      categoryId: 12,
    },
    {
      lName: "Лукпанова",
      fName: "А",
      sName: "С",
      zvanieId: 4,
      podrazdelenieId: 17,
      isMale: false,
      categoryId: 13,
    },

    // РОиО || Солдаты срочной службы
    {
      lName: "Кабиденов",
      fName: "Д",
      sName: "М",
      zvanieId: 1,
      podrazdelenieId: 18,
      isMale: true,
      categoryId: 18,
    },
    {
      lName: "Халелов",
      fName: "А",
      sName: "А",
      zvanieId: 1,
      podrazdelenieId: 18,
      isMale: true,
      categoryId: 18,
    },
    {
      lName: "Слямгазинов",
      fName: "М",
      sName: "М",
      zvanieId: 1,
      podrazdelenieId: 18,
      isMale: true,
      categoryId: 18,
    },
    {
      lName: "Ергали",
      fName: "Д",
      sName: "Н",
      zvanieId: 1,
      podrazdelenieId: 18,
      isMale: true,
      categoryId: 18,
    },
    {
      lName: "Алибек",
      fName: "Ғ",
      sName: "",
      zvanieId: 1,
      podrazdelenieId: 18,
      isMale: true,
      categoryId: 18,
    },
    {
      lName: "Бектенов",
      fName: "Д",
      sName: "Е",
      zvanieId: 1,
      podrazdelenieId: 18,
      isMale: true,
      categoryId: 18,
    },
    {
      lName: "Сайранбеков",
      fName: "Ш",
      sName: "А",
      zvanieId: 1,
      podrazdelenieId: 18,
      isMale: true,
      categoryId: 18,
    },
    {
      lName: "Сатыбай",
      fName: "Б",
      sName: "М",
      zvanieId: 1,
      podrazdelenieId: 18,
      isMale: true,
      categoryId: 18,
    },
    {
      lName: "Берікханов",
      fName: "М",
      sName: "С",
      zvanieId: 1,
      podrazdelenieId: 18,
      isMale: true,
      categoryId: 18,
    },
    {
      lName: "Олжабеков",
      fName: "Д",
      sName: "М",
      zvanieId: 1,
      podrazdelenieId: 18,
      isMale: true,
      categoryId: 18,
    },
    {
      lName: "Құдайбергенов",
      fName: "І",
      sName: "Қ",
      zvanieId: 1,
      podrazdelenieId: 18,
      isMale: true,
      categoryId: 18,
    },
    {
      lName: "Алиев",
      fName: "Н",
      sName: "Б",
      zvanieId: 1,
      podrazdelenieId: 18,
      isMale: true,
      categoryId: 18,
    },
    {
      lName: "Токенов",
      fName: "Н",
      sName: "А",
      zvanieId: 1,
      podrazdelenieId: 18,
      isMale: true,
      categoryId: 18,
    },
    {
      lName: "Кумаров",
      fName: "А",
      sName: "Н",
      zvanieId: 1,
      podrazdelenieId: 18,
      isMale: true,
      categoryId: 18,
    },

    //
    // { lName: "", fName: "", sName: "", zvanieId:  , podrazdelenieId: },
  ]);
};

const fillDefaultsZvanie = () => {
  Zvanie.bulkCreate([
    { id: 1, name: "Рядовой" },
    { id: 2, name: "Ефрейтор" },
    { id: 3, name: "Младший сержант" },
    { id: 4, name: "Сержант" },
    { id: 5, name: "Старший сержант" },
    { id: 6, name: "Сержант третьего класса" },
    { id: 7, name: "Сержант второго класса" },
    { id: 8, name: "Сержант первого класса" },
    { id: 9, name: "Штаб-сержант" },
    { id: 10, name: "Мастер-сержант" },

    { id: 11, name: "Лейтенант" },
    { id: 12, name: "Старший лейтенант" },
    { id: 13, name: "Капитан" },
    { id: 14, name: "Майор" },
    { id: 15, name: "Подполковник" },
    { id: 16, name: "Полковник" },
    { id: 17, name: "Генерал-майор" },
    { id: 18, name: "Генерал-лейтенант" },
    { id: 19, name: "Генерал-полковник" },
    { id: 20, name: "Генерал армии" },

    { id: 21, name: "Матрос" },
    { id: 22, name: "Старший матрос" },
    { id: 23, name: "Старшина второй статьи" },
    { id: 24, name: "Старшина первой статьи" },
    { id: 25, name: "Главный старшина" },
    { id: 26, name: "Старшина третьего класса" },
    { id: 27, name: "Старшина второго класса" },
    { id: 28, name: "Старшина первого класса" },
    { id: 29, name: "Штаб-старшина" },
    { id: 30, name: "Мастер-старшина" },

    { id: 31, name: "Капитан-лейтенант" },
    { id: 32, name: "Капитан третьего ранга" },
    { id: 33, name: "Капитан второго ранга" },
    { id: 34, name: "Капитан первого ранга" },
    { id: 35, name: "Контр-адмирал" },
    { id: 36, name: "Вице-адмирал" },
    { id: 37, name: "Адмирал" },

    { id: 38, name: "Старшина" },
  ]);
};

const fillDefaultsCategories = () => {
  Category.bulkCreate([
    { id: 1, name: "Первая среди мужчин", shortName: "1(м)" },
    { id: 2, name: "Вторая среди мужчин", shortName: "2(м)" },
    { id: 3, name: "Третья среди мужчин", shortName: "3(м)" },
    { id: 4, name: "Четвертая среди мужчин", shortName: "4(м)" },
    { id: 5, name: "Пятая среди мужчин", shortName: "5(м)" },
    { id: 6, name: "Шестая среди мужчин", shortName: "6(м)" },
    { id: 7, name: "Седьмая среди мужчин", shortName: "7(м)" },
    { id: 8, name: "Восьмая среди мужчин", shortName: "8(м)" },
    { id: 9, name: "Первая среди женщин", shortName: "1(ж)" },
    { id: 10, name: "Вторая среди женщин", shortName: "2(ж)" },
    { id: 11, name: "Третья среди женщин", shortName: "3(ж)" },
    { id: 12, name: "Четвертая среди женщин", shortName: "4(ж)" },
    { id: 13, name: "Пятая среди женщин", shortName: "5(ж)" },
    { id: 14, name: "Шестая среди женщин", shortName: "6(ж)" },
    { id: 15, name: "Седьмая среди женщин", shortName: "7(ж)" },
    { id: 16, name: "Восьмая среди женщин", shortName: "8(ж)" },
    {
      id: 17,
      name: "Солдаты срочной службы до 6 месяцев",
      shortName: "до 6 мес.",
    },
    {
      id: 18,
      name: "Солдаты срочной службы после 6 месяцев",
      shortName: "после 6 мес.",
    },
    {
      id: 19,
      name: "Гражданский юноша",
      shortName: "юноша",
    },
    {
      id: 20,
      name: "Первая среди специалистов физической подготовки и спорта",
      shortName: "1(СФПиС)",
    },
    {
      id: 21,
      name: "Вторая среди специалистов физической подготовки и спорта",
      shortName: "2(СФПиС)",
    },
    {
      id: 22,
      name: "Третья среди специалистов физической подготовки и спорта",
      shortName: "3(СФПиС)",
    },
    {
      id: 23,
      name: "Четвертая среди специалистов физической подготовки и спорта",
      shortName: "4(СФПиС)",
    },
    {
      id: 24,
      name: "Пятая среди специалистов физической подготовки и спорта",
      shortName: "5(СФПиС)",
    },
    {
      id: 25,
      name: "Шестая среди специалистов физической подготовки и спорта",
      shortName: "6(СФПиС)",
    },
    {
      id: 26,
      name: "Седьмая среди специалистов физической подготовки и спорта",
      shortName: "7(СФПиС)",
    },
    {
      id: 27,
      name: "Восьмая среди специалистов физической подготовки и спорта",
      shortName: "8(СФПиС)",
    },
  ]);
};

const fillDefaultsUprazhnenieRealValuesTypes = () => {
  UprazhnenieRealValuesType.bulkCreate([
    { id: 1, name: "Секунда", shortName: "сек." },
    { id: 2, name: "Количество повторений", shortName: "кол-во повт-й" },
    { id: 3, name: "Цикл", shortName: "цикл(ов)" },
  ]);
};

const fillDefaultsUprazhneniya = () => {
  Uprazhnenie.bulkCreate([
    {
      id: 1,
      name: "Подтягивание на перекладине",
      shortName: "3",
      uprazhnenieRealValuesTypeId: 2,
      step: 1,
      valueToAddAfterMaxResult: 10,
      EfficiencyPreferenceId: 1,
    },
    {
      id: 2,
      name: "Поднимание ног к перекладине",
      shortName: "4",
      uprazhnenieRealValuesTypeId: 2,
      step: 1,
      valueToAddAfterMaxResult: 5,
      EfficiencyPreferenceId: 1,
    },
    {
      id: 3,
      name: "Подъем переворотом на перекладине",
      shortName: "5",
      uprazhnenieRealValuesTypeId: 2,
      step: 1,
      valueToAddAfterMaxResult: 5,
      EfficiencyPreferenceId: 1,
    },
    {
      id: 4,
      name: "Подъем силой на перекладине",
      shortName: "6",
      uprazhnenieRealValuesTypeId: 2,
      step: 1,
      valueToAddAfterMaxResult: 5,
      EfficiencyPreferenceId: 1,
    },
    {
      id: 5,
      name: "Комбинированное силовое упражнение на перекладине",
      shortName: "7",
      uprazhnenieRealValuesTypeId: 3,
      step: 1,
      valueToAddAfterMaxResult: 20,
      EfficiencyPreferenceId: 1,
    },
    {
      id: 6,
      name: "Сгибание и разгибание рук в упоре на брусьях",
      shortName: "8",
      uprazhnenieRealValuesTypeId: 2,
      step: 1,
      valueToAddAfterMaxResult: 5,
      EfficiencyPreferenceId: 1,
    },
    {
      id: 7,
      name: "Угол в упоре на брусьях",
      shortName: "9",
      uprazhnenieRealValuesTypeId: 1,
      step: 1,
      valueToAddAfterMaxResult: 5,
      EfficiencyPreferenceId: 1,
    },
    {
      id: 8,
      name: "Поднимание гири 24 килограмм (рывок)",
      shortName: "15",
      uprazhnenieRealValuesTypeId: 2,
      step: 1,
      valueToAddAfterMaxResult: 5,
      EfficiencyPreferenceId: 1,
    },
    {
      id: 9,
      name: "Комплексное силовое упражнение (Военнослужащие - мужчины)",
      shortName: "16(м)",
      uprazhnenieRealValuesTypeId: 2,
      step: 1,
      valueToAddAfterMaxResult: 2,
      EfficiencyPreferenceId: 1,
    },
    {
      id: 10,
      name: "Комплексное силовое упражнение (Военнослужащие - женщины)",
      shortName: "16(ж)",
      uprazhnenieRealValuesTypeId: 2,
      step: 1,
      valueToAddAfterMaxResult: 5,
      EfficiencyPreferenceId: 1,
    },
    {
      id: 11,
      name: "Комплексное силовое упражнение (Cпециалисты физической подготовки и спорта)",
      shortName: "16(СФПиС)",
      uprazhnenieRealValuesTypeId: 2,
      step: 1,
      valueToAddAfterMaxResult: 2,
      EfficiencyPreferenceId: 1,
    },
    {
      id: 12,
      name: "Упражнение на стационарном колесе",
      shortName: "19",
      uprazhnenieRealValuesTypeId: undefined,
      step: undefined,
      valueToAddAfterMaxResult: undefined,
      EfficiencyPreferenceId: undefined,
    },
    {
      id: 13,
      name: "Упражнение на лопинге",
      shortName: "21",
      uprazhnenieRealValuesTypeId: undefined,
      step: undefined,
      valueToAddAfterMaxResult: undefined,
      EfficiencyPreferenceId: undefined,
    },
    {
      id: 14,
      name: "Общее контрольное упражнение на единой полосе препятствий",
      shortName: "27",
      uprazhnenieRealValuesTypeId: undefined,
      step: undefined,
      valueToAddAfterMaxResult: undefined,
      EfficiencyPreferenceId: undefined,
    },
    {
      id: 15,
      name: "Специальное контрольное упражнение для военных учебных заведений",
      shortName: "28",
      uprazhnenieRealValuesTypeId: undefined,
      step: undefined,
      valueToAddAfterMaxResult: undefined,
      EfficiencyPreferenceId: undefined,
    },
    {
      id: 16,
      name: "Специальное контрольное упражнение для личного состава Десантно-штурмовых войск",
      shortName: "29",
      uprazhnenieRealValuesTypeId: undefined,
      step: undefined,
      valueToAddAfterMaxResult: undefined,
      EfficiencyPreferenceId: undefined,
    },
    {
      id: 17,
      name: "Преодоление единой полосы препятствий в составе подразделения (для военных учебных заведений)",
      shortName: "30",
      uprazhnenieRealValuesTypeId: undefined,
      step: undefined,
      valueToAddAfterMaxResult: undefined,
      EfficiencyPreferenceId: undefined,
    },
    {
      id: 18,
      name: "Бег с преодолением полосы препятствий в составе подразделения (для военных учебных заведений)",
      shortName: "31",
      uprazhnenieRealValuesTypeId: undefined,
      step: undefined,
      valueToAddAfterMaxResult: undefined,
      EfficiencyPreferenceId: undefined,
    },
    {
      id: 19,
      name: "Специальное контрольное упражнение для личного состава подразделений, предназначенных для действий в горах",
      shortName: "32",
      uprazhnenieRealValuesTypeId: undefined,
      step: undefined,
      valueToAddAfterMaxResult: undefined,
      EfficiencyPreferenceId: undefined,
    },
    {
      id: 20,
      name: "Специальное контрольное упражнение для личного состава надводных кораблей",
      shortName: "33",
      uprazhnenieRealValuesTypeId: undefined,
      step: undefined,
      valueToAddAfterMaxResult: undefined,
      EfficiencyPreferenceId: undefined,
    },
    {
      id: 21,
      name: "Бег на 100 метров",
      shortName: "34",
      uprazhnenieRealValuesTypeId: undefined,
      step: undefined,
      valueToAddAfterMaxResult: undefined,
      EfficiencyPreferenceId: undefined,
    },
    {
      id: 22,
      name: "Челночный бег 10х10 метров",
      shortName: "35",
      uprazhnenieRealValuesTypeId: undefined,
      step: undefined,
      valueToAddAfterMaxResult: undefined,
      EfficiencyPreferenceId: undefined,
    },
    {
      id: 23,
      name: "Бег на 400 метров",
      shortName: "36",
      uprazhnenieRealValuesTypeId: undefined,
      step: undefined,
      valueToAddAfterMaxResult: undefined,
      EfficiencyPreferenceId: undefined,
    },
    {
      id: 24,
      name: "Бег на 1000 метров",
      shortName: "37",
      uprazhnenieRealValuesTypeId: undefined,
      step: undefined,
      valueToAddAfterMaxResult: undefined,
      EfficiencyPreferenceId: undefined,
    },
    {
      id: 25,
      name: "Бег на 3000 метров",
      shortName: "38",
      uprazhnenieRealValuesTypeId: undefined,
      step: undefined,
      valueToAddAfterMaxResult: undefined,
      EfficiencyPreferenceId: undefined,
    },
    {
      id: 26,
      name: "Бег на 5000 метров",
      shortName: "39",
      uprazhnenieRealValuesTypeId: undefined,
      step: undefined,
      valueToAddAfterMaxResult: undefined,
      EfficiencyPreferenceId: undefined,
    },
    {
      id: 27,
      name: "Метание гранаты Ф – 1 (600 грамм) на дальность",
      shortName: "40",
      uprazhnenieRealValuesTypeId: undefined,
      step: undefined,
      valueToAddAfterMaxResult: undefined,
      EfficiencyPreferenceId: undefined,
    },
    {
      id: 28,
      name: "Марш-бросок на 5 километров",
      shortName: "42",
      uprazhnenieRealValuesTypeId: undefined,
      step: undefined,
      valueToAddAfterMaxResult: undefined,
      EfficiencyPreferenceId: undefined,
    },
    {
      id: 29,
      name: "Марш-бросок на 10 километров",
      shortName: "43",
      uprazhnenieRealValuesTypeId: undefined,
      step: undefined,
      valueToAddAfterMaxResult: undefined,
      EfficiencyPreferenceId: undefined,
    },
    {
      id: 30,
      name: "Лыжная гонка на 5 километров",
      shortName: "44",
      uprazhnenieRealValuesTypeId: undefined,
      step: undefined,
      valueToAddAfterMaxResult: undefined,
      EfficiencyPreferenceId: undefined,
    },
    {
      id: 31,
      name: "Лыжная гонка на 10 километров",
      shortName: "45",
      uprazhnenieRealValuesTypeId: undefined,
      step: undefined,
      valueToAddAfterMaxResult: undefined,
      EfficiencyPreferenceId: undefined,
    },
    {
      id: 32,
      name: "Марш на лыжах 5 километров в составе подразделения",
      shortName: "46",
      uprazhnenieRealValuesTypeId: undefined,
      step: undefined,
      valueToAddAfterMaxResult: undefined,
      EfficiencyPreferenceId: undefined,
    },
    {
      id: 33,
      name: "Марш на лыжах 10 километров в составе подразделения",
      shortName: "47",
      uprazhnenieRealValuesTypeId: undefined,
      step: undefined,
      valueToAddAfterMaxResult: undefined,
      EfficiencyPreferenceId: undefined,
    },
    {
      id: 34,
      name: "Плавание на 100 метров в спортивной форме",
      shortName: "48",
      uprazhnenieRealValuesTypeId: undefined,
      step: undefined,
      valueToAddAfterMaxResult: undefined,
      EfficiencyPreferenceId: undefined,
    },
    {
      id: 35,
      name: "Плавание в обмундировании с оружием",
      shortName: "49",
      uprazhnenieRealValuesTypeId: undefined,
      step: undefined,
      valueToAddAfterMaxResult: undefined,
      EfficiencyPreferenceId: undefined,
    },
    {
      id: 36,
      name: "Ныряние в длину",
      shortName: "50",
      uprazhnenieRealValuesTypeId: undefined,
      step: undefined,
      valueToAddAfterMaxResult: undefined,
      EfficiencyPreferenceId: undefined,
    },
  ]);
};

const fillDefaultsUprazhnenieStandards = () => {
  UprazhnenieStandard.bulkCreate([
    { uprazhnenieId: 1, categoryId: 1, value: 17, result: 60 },
    { uprazhnenieId: 1, categoryId: 2, value: 16, result: 60 },
    { uprazhnenieId: 1, categoryId: 3, value: 15, result: 60 },
    { uprazhnenieId: 1, categoryId: 4, value: 10, result: 60 },
    { uprazhnenieId: 1, categoryId: 5, value: 8, result: 60 },
    { uprazhnenieId: 1, categoryId: 6, value: 7, result: 60 },
    { uprazhnenieId: 1, categoryId: 7, value: 6, result: 60 },
    { uprazhnenieId: 1, categoryId: 8, value: 4, result: 60 },
    { uprazhnenieId: 1, categoryId: 17, value: 14, result: 60 },
    { uprazhnenieId: 1, categoryId: 18, value: 15, result: 60 },
    { uprazhnenieId: 1, categoryId: 19, value: 14, result: 60 },
    { uprazhnenieId: 1, categoryId: 1, value: 16, result: 55 },
    { uprazhnenieId: 1, categoryId: 2, value: 15, result: 55 },
    { uprazhnenieId: 1, categoryId: 3, value: 14, result: 55 },
    { uprazhnenieId: 1, categoryId: 17, value: 13, result: 55 },
    { uprazhnenieId: 1, categoryId: 18, value: 14, result: 55 },
    { uprazhnenieId: 1, categoryId: 19, value: 13, result: 55 },
    { uprazhnenieId: 1, categoryId: 1, value: 15, result: 50 },
    { uprazhnenieId: 1, categoryId: 2, value: 14, result: 50 },
    { uprazhnenieId: 1, categoryId: 3, value: 13, result: 50 },
    { uprazhnenieId: 1, categoryId: 4, value: 9, result: 50 },
    { uprazhnenieId: 1, categoryId: 5, value: 7, result: 50 },
    { uprazhnenieId: 1, categoryId: 6, value: 6, result: 50 },
    { uprazhnenieId: 1, categoryId: 7, value: 5, result: 50 },
    { uprazhnenieId: 1, categoryId: 17, value: 12, result: 50 },
    { uprazhnenieId: 1, categoryId: 18, value: 13, result: 50 },
    { uprazhnenieId: 1, categoryId: 19, value: 12, result: 50 },
    { uprazhnenieId: 1, categoryId: 1, value: 14, result: 45 },
    { uprazhnenieId: 1, categoryId: 2, value: 13, result: 45 },
    { uprazhnenieId: 1, categoryId: 3, value: 12, result: 45 },
    { uprazhnenieId: 1, categoryId: 17, value: 11, result: 45 },
    { uprazhnenieId: 1, categoryId: 18, value: 12, result: 45 },
    { uprazhnenieId: 1, categoryId: 19, value: 11, result: 45 },
    { uprazhnenieId: 1, categoryId: 1, value: 13, result: 40 },
    { uprazhnenieId: 1, categoryId: 2, value: 12, result: 40 },
    { uprazhnenieId: 1, categoryId: 3, value: 11, result: 40 },
    { uprazhnenieId: 1, categoryId: 4, value: 8, result: 40 },
    { uprazhnenieId: 1, categoryId: 5, value: 6, result: 40 },
    { uprazhnenieId: 1, categoryId: 6, value: 5, result: 40 },
    { uprazhnenieId: 1, categoryId: 7, value: 4, result: 40 },
    { uprazhnenieId: 1, categoryId: 8, value: 3, result: 40 },
    { uprazhnenieId: 1, categoryId: 17, value: 10, result: 40 },
    { uprazhnenieId: 1, categoryId: 18, value: 11, result: 40 },
    { uprazhnenieId: 1, categoryId: 19, value: 10, result: 40 },
    { uprazhnenieId: 1, categoryId: 1, value: 12, result: 35 },
    { uprazhnenieId: 1, categoryId: 2, value: 11, result: 35 },
    { uprazhnenieId: 1, categoryId: 3, value: 10, result: 35 },
    { uprazhnenieId: 1, categoryId: 17, value: 9, result: 35 },
    { uprazhnenieId: 1, categoryId: 18, value: 10, result: 35 },
    { uprazhnenieId: 1, categoryId: 19, value: 9, result: 35 },
    { uprazhnenieId: 1, categoryId: 1, value: 11, result: 30 },
    { uprazhnenieId: 1, categoryId: 2, value: 10, result: 30 },
    { uprazhnenieId: 1, categoryId: 3, value: 9, result: 30 },
    { uprazhnenieId: 1, categoryId: 4, value: 7, result: 30 },
    { uprazhnenieId: 1, categoryId: 5, value: 5, result: 30 },
    { uprazhnenieId: 1, categoryId: 6, value: 4, result: 30 },
    { uprazhnenieId: 1, categoryId: 7, value: 3, result: 30 },
    { uprazhnenieId: 1, categoryId: 17, value: 8, result: 30 },
    { uprazhnenieId: 1, categoryId: 18, value: 9, result: 30 },
    { uprazhnenieId: 1, categoryId: 19, value: 8, result: 30 },
    { uprazhnenieId: 1, categoryId: 1, value: 10, result: 25 },
    { uprazhnenieId: 1, categoryId: 2, value: 9, result: 25 },
    { uprazhnenieId: 1, categoryId: 3, value: 8, result: 25 },
    { uprazhnenieId: 1, categoryId: 17, value: 7, result: 25 },
    { uprazhnenieId: 1, categoryId: 18, value: 8, result: 25 },
    { uprazhnenieId: 1, categoryId: 19, value: 7, result: 25 },
    { uprazhnenieId: 1, categoryId: 1, value: 9, result: 20 },
    { uprazhnenieId: 1, categoryId: 2, value: 8, result: 20 },
    { uprazhnenieId: 1, categoryId: 3, value: 7, result: 20 },
    { uprazhnenieId: 1, categoryId: 4, value: 6, result: 20 },
    { uprazhnenieId: 1, categoryId: 5, value: 4, result: 20 },
    { uprazhnenieId: 1, categoryId: 6, value: 3, result: 20 },
    { uprazhnenieId: 1, categoryId: 7, value: 2, result: 20 },
    { uprazhnenieId: 1, categoryId: 8, value: 2, result: 20 },
    { uprazhnenieId: 1, categoryId: 17, value: 6, result: 20 },
    { uprazhnenieId: 1, categoryId: 18, value: 7, result: 20 },
    { uprazhnenieId: 1, categoryId: 19, value: 6, result: 20 },
    { uprazhnenieId: 1, categoryId: 20, value: 20, result: 60 },
    { uprazhnenieId: 1, categoryId: 21, value: 19, result: 60 },
    { uprazhnenieId: 1, categoryId: 22, value: 18, result: 60 },
    { uprazhnenieId: 1, categoryId: 23, value: 13, result: 60 },
    { uprazhnenieId: 1, categoryId: 24, value: 12, result: 60 },
    { uprazhnenieId: 1, categoryId: 25, value: 11, result: 60 },
    { uprazhnenieId: 1, categoryId: 26, value: 10, result: 60 },
    { uprazhnenieId: 1, categoryId: 27, value: 9, result: 60 },
    { uprazhnenieId: 1, categoryId: 20, value: 19, result: 55 },
    { uprazhnenieId: 1, categoryId: 21, value: 18, result: 55 },
    { uprazhnenieId: 1, categoryId: 22, value: 17, result: 55 },
    { uprazhnenieId: 1, categoryId: 20, value: 18, result: 50 },
    { uprazhnenieId: 1, categoryId: 21, value: 17, result: 50 },
    { uprazhnenieId: 1, categoryId: 22, value: 16, result: 50 },
    { uprazhnenieId: 1, categoryId: 23, value: 12, result: 50 },
    { uprazhnenieId: 1, categoryId: 24, value: 11, result: 50 },
    { uprazhnenieId: 1, categoryId: 25, value: 10, result: 50 },
    { uprazhnenieId: 1, categoryId: 26, value: 9, result: 50 },
    { uprazhnenieId: 1, categoryId: 27, value: 8, result: 50 },
    { uprazhnenieId: 1, categoryId: 20, value: 17, result: 45 },
    { uprazhnenieId: 1, categoryId: 21, value: 16, result: 45 },
    { uprazhnenieId: 1, categoryId: 22, value: 15, result: 45 },
    { uprazhnenieId: 1, categoryId: 20, value: 16, result: 40 },
    { uprazhnenieId: 1, categoryId: 21, value: 15, result: 40 },
    { uprazhnenieId: 1, categoryId: 22, value: 14, result: 40 },
    { uprazhnenieId: 1, categoryId: 23, value: 11, result: 40 },
    { uprazhnenieId: 1, categoryId: 24, value: 10, result: 40 },
    { uprazhnenieId: 1, categoryId: 25, value: 9, result: 40 },
    { uprazhnenieId: 1, categoryId: 26, value: 8, result: 40 },
    { uprazhnenieId: 1, categoryId: 27, value: 7, result: 40 },
    { uprazhnenieId: 1, categoryId: 20, value: 15, result: 35 },
    { uprazhnenieId: 1, categoryId: 21, value: 14, result: 35 },
    { uprazhnenieId: 1, categoryId: 22, value: 13, result: 35 },
    { uprazhnenieId: 1, categoryId: 20, value: 14, result: 30 },
    { uprazhnenieId: 1, categoryId: 21, value: 13, result: 30 },
    { uprazhnenieId: 1, categoryId: 22, value: 12, result: 30 },
    { uprazhnenieId: 1, categoryId: 23, value: 10, result: 30 },
    { uprazhnenieId: 1, categoryId: 24, value: 9, result: 30 },
    { uprazhnenieId: 1, categoryId: 25, value: 8, result: 30 },
    { uprazhnenieId: 1, categoryId: 26, value: 7, result: 30 },
    { uprazhnenieId: 1, categoryId: 27, value: 6, result: 30 },
    { uprazhnenieId: 1, categoryId: 20, value: 13, result: 25 },
    { uprazhnenieId: 1, categoryId: 21, value: 12, result: 25 },
    { uprazhnenieId: 1, categoryId: 22, value: 11, result: 25 },
    { uprazhnenieId: 1, categoryId: 20, value: 12, result: 20 },
    { uprazhnenieId: 1, categoryId: 21, value: 11, result: 20 },
    { uprazhnenieId: 1, categoryId: 22, value: 10, result: 20 },
    { uprazhnenieId: 1, categoryId: 23, value: 9, result: 20 },
    { uprazhnenieId: 1, categoryId: 24, value: 8, result: 20 },
    { uprazhnenieId: 1, categoryId: 25, value: 7, result: 20 },
    { uprazhnenieId: 1, categoryId: 26, value: 6, result: 20 },
    { uprazhnenieId: 1, categoryId: 27, value: 4, result: 20 },
    { uprazhnenieId: 2, categoryId: 1, value: 17, result: 60 },
    { uprazhnenieId: 2, categoryId: 2, value: 16, result: 60 },
    { uprazhnenieId: 2, categoryId: 3, value: 15, result: 60 },
    { uprazhnenieId: 2, categoryId: 4, value: 14, result: 60 },
    { uprazhnenieId: 2, categoryId: 17, value: 14, result: 60 },
    { uprazhnenieId: 2, categoryId: 18, value: 15, result: 60 },
    { uprazhnenieId: 2, categoryId: 19, value: 14, result: 60 },
    { uprazhnenieId: 2, categoryId: 1, value: 16, result: 55 },
    { uprazhnenieId: 2, categoryId: 2, value: 15, result: 55 },
    { uprazhnenieId: 2, categoryId: 3, value: 14, result: 55 },
    { uprazhnenieId: 2, categoryId: 4, value: 13, result: 55 },
    { uprazhnenieId: 2, categoryId: 17, value: 13, result: 55 },
    { uprazhnenieId: 2, categoryId: 18, value: 14, result: 55 },
    { uprazhnenieId: 2, categoryId: 19, value: 13, result: 55 },
    { uprazhnenieId: 2, categoryId: 1, value: 15, result: 50 },
    { uprazhnenieId: 2, categoryId: 2, value: 14, result: 50 },
    { uprazhnenieId: 2, categoryId: 3, value: 13, result: 50 },
    { uprazhnenieId: 2, categoryId: 4, value: 12, result: 50 },
    { uprazhnenieId: 2, categoryId: 17, value: 12, result: 50 },
    { uprazhnenieId: 2, categoryId: 18, value: 13, result: 50 },
    { uprazhnenieId: 2, categoryId: 19, value: 12, result: 50 },
    { uprazhnenieId: 2, categoryId: 1, value: 14, result: 45 },
    { uprazhnenieId: 2, categoryId: 2, value: 13, result: 45 },
    { uprazhnenieId: 2, categoryId: 3, value: 12, result: 45 },
    { uprazhnenieId: 2, categoryId: 4, value: 11, result: 45 },
    { uprazhnenieId: 2, categoryId: 17, value: 11, result: 45 },
    { uprazhnenieId: 2, categoryId: 18, value: 12, result: 45 },
    { uprazhnenieId: 2, categoryId: 19, value: 11, result: 45 },
    { uprazhnenieId: 2, categoryId: 1, value: 13, result: 40 },
    { uprazhnenieId: 2, categoryId: 2, value: 12, result: 40 },
    { uprazhnenieId: 2, categoryId: 3, value: 11, result: 40 },
    { uprazhnenieId: 2, categoryId: 4, value: 10, result: 40 },
    { uprazhnenieId: 2, categoryId: 17, value: 10, result: 40 },
    { uprazhnenieId: 2, categoryId: 18, value: 11, result: 40 },
    { uprazhnenieId: 2, categoryId: 19, value: 10, result: 40 },
    { uprazhnenieId: 2, categoryId: 1, value: 12, result: 35 },
    { uprazhnenieId: 2, categoryId: 2, value: 11, result: 35 },
    { uprazhnenieId: 2, categoryId: 3, value: 10, result: 35 },
    { uprazhnenieId: 2, categoryId: 4, value: 9, result: 35 },
    { uprazhnenieId: 2, categoryId: 17, value: 9, result: 35 },
    { uprazhnenieId: 2, categoryId: 18, value: 10, result: 35 },
    { uprazhnenieId: 2, categoryId: 19, value: 9, result: 35 },
    { uprazhnenieId: 2, categoryId: 1, value: 11, result: 30 },
    { uprazhnenieId: 2, categoryId: 2, value: 10, result: 30 },
    { uprazhnenieId: 2, categoryId: 3, value: 9, result: 30 },
    { uprazhnenieId: 2, categoryId: 4, value: 8, result: 30 },
    { uprazhnenieId: 2, categoryId: 17, value: 8, result: 30 },
    { uprazhnenieId: 2, categoryId: 18, value: 9, result: 30 },
    { uprazhnenieId: 2, categoryId: 19, value: 8, result: 30 },
    { uprazhnenieId: 2, categoryId: 1, value: 10, result: 25 },
    { uprazhnenieId: 2, categoryId: 2, value: 9, result: 25 },
    { uprazhnenieId: 2, categoryId: 3, value: 8, result: 25 },
    { uprazhnenieId: 2, categoryId: 4, value: 7, result: 25 },
    { uprazhnenieId: 2, categoryId: 17, value: 7, result: 25 },
    { uprazhnenieId: 2, categoryId: 18, value: 8, result: 25 },
    { uprazhnenieId: 2, categoryId: 19, value: 7, result: 25 },
    { uprazhnenieId: 2, categoryId: 1, value: 9, result: 20 },
    { uprazhnenieId: 2, categoryId: 2, value: 8, result: 20 },
    { uprazhnenieId: 2, categoryId: 3, value: 7, result: 20 },
    { uprazhnenieId: 2, categoryId: 4, value: 6, result: 20 },
    { uprazhnenieId: 2, categoryId: 17, value: 6, result: 20 },
    { uprazhnenieId: 2, categoryId: 18, value: 7, result: 20 },
    { uprazhnenieId: 2, categoryId: 19, value: 6, result: 20 },
  ]);
};
module.exports = {
  fillDefaultsEfficiencyPreferences,
  fillDefaultsPodrazdeleniya,
  fillDefaultsPersons,
  fillDefaultsZvanie,
  fillDefaultsCategories,
  fillDefaultsUprazhnenieRealValuesTypes,
  fillDefaultsUprazhneniya,
  fillDefaultsUprazhnenieStandards,
};
